module.exports = {
  'id': String,
  'user': String,
  'brand': String,
  'google_credential': String,
  'synced_messages_num': Number,
  'messages_total': Number,
  'synced_threads_num': Number,
  'threads_total': Number,
  'synced_contacts_num': Number,
  'contacts_total': Number,
  'sync_duration': Number,
  'status': Boolean,
  'created_at': Date,
  'updated_at': Date,
  'deleted_at': Date,
  'glsh': String,
  'ord': String,
  'type': String,

}