module.exports = {
  "address": {
    "title": "",
    "subtitle": "",
    "street_name": "Tananger Springs",
    "city": "Denison",
    "state": "Texas",
    "state_code": "Texas",
    "postal_code": "75021",
    "neighborhood": "",
    "street_suffix": "Drive",
    "street_number": "341",
    "unit_number": "",
    "country": "United States",
    "country_code": "USA",
    "matrix_unique_id": 66792091,
    "county_or_parish": "Grayson",
    "directions": "FROM TEXOMA PARKWAY (HWY 91) GO EAST ON WOODLAWN ROAD TO ENTRANCE",
    "street_dir_prefix": "",
    "street_dir_suffix": "",
    "street_number_searchable": "341"
  },
  "property": {
    "description": "BEAUTIFUL ONE ACRE TREED BUILDING SITE IN GATED TANANAGER SPRINGS SUBDIVISION.  SHERMAN SCHOOL DISTRICT. LOCATED ACROSS FROM WOODLAWN COUNTRYCLUB. HOMEOWNERS DUTES INCLUDES A SOCIAL MEMBERSHIP (CLUB AND POOL PRIVILEGES)IN WOODLAWN COUNTRY CLUB.  DRIVE YOUR CART ACROSS THE STREET TO PLAY A ROUND. CALL AGENT REGARDING OWNER FINANCING.",
    "square_meters": 0,
    "building_square_meters": 0,
    "lot_square_meters": 4046.8227424749166,
    "property_type": "Residential",
    "property_subtype": "RES-Single Family",
    "matrix_unique_id": 66792091,
    "heating": "{}",
    "flooring": "{}",
    "utilities": "{Asphalt,Co-op Water,Outside City Limits,Private Road}",
    "utilities_other": "{Cable Available,Electric,Electric Avail. Off Site,Natural Gas,Septic System Required}",
    "architectural_style": "{}",
    "structural_style": "",
    "lot_number": "9",
    "soil_type": "",
    "construction_materials": "",
    "construction_materials_walls": "",
    "foundation_details": "",
    "roof": "",
    "pool_yn": false,
    "handicap_yn": false,
    "elementary_school_name": "Percy W Neblett",
    "intermediate_school_name": "Dillingham",
    "high_school_name": "Sherman",
    "junior_high_school_name": "",
    "middle_school_name": "Piner",
    "primary_school_name": "",
    "senior_high_school_name": "",
    "school_district": "Sherman ISD",
    "subdivision_name": "Tananger Spgs Add",
    "accessibility_features": "{}",
    "bedroom_bathroom_features": "{}",
    "commercial_features": "{}",
    "community_features": "{Gated Entrance}",
    "energysaving_features": "{}",
    "exterior_features": "{}",
    "interior_features": "{}",
    "farmranch_features": "{}",
    "fireplace_features": "{}",
    "lot_features": "{Acreage,Heavily Treed,Interior Lot,Subdivision}",
    "parking_features": "{}",
    "pool_features": "{}",
    "security_features": "{}",
    "appliances_yn": false,
    "building_number": "",
    "green_building_certification": "",
    "green_energy_efficient": "",
    "lot_size": 1,
    "lot_size_area": 43560,
    "lot_size_dimensions": "176.3X247",
    "map_coordinates": "M",
    "pets_yn": false,
    "photo_count": 6,
    "subdivided_yn": false,
    "surface_rights": "",
    "year_built_details": "",
    "zoning": "Rural Residential",
    "security_system_yn": false,
    "address": {
      "city": "Dallas",
      "street_name": "Gulden",
      "street_suffix": "Lane",
      "street_dir_prefix": "",
      "street_dir_suffix": "",
      "state": "Texas",
      "postal_code": "75212"
    }
  },
  "listing": {
    "currency": "USD",
    "price": 309000,
    "status": "Active",
    "matrix_unique_id": 66792091,
    "last_price": 45000,
    "original_price": 60000,
    "association_fee": 480,
    "association_fee_frequency": "Annual",
    "association_fee_includes": "Other,Partial Use of Facilities,Reserves",
    "association_type": "Mandatory",
    "mls_number": "13511611",
    "financing_proposed": "Cash,Conventional,Owner Carry First",
    "list_date": "2013-10-07T00:00:00.000",
    "list_office_mui": 15505703,
    "list_office_mls_id": "GILB00TO",
    "list_office_name": "C-21  DEAN GILBERT, REALTORS",
    "list_office_phone": "(903) 893-5188",
    "co_list_office_mui": -1,
    "co_list_office_mls_id": "",
    "co_list_office_name": "",
    "co_list_office_phone": "",
    "selling_office_mui": -1,
    "selling_office_mls_id": "",
    "selling_office_name": "",
    "selling_office_phone": "",
    "co_selling_office_mui": -1,
    "co_selling_office_mls_id": "",
    "co_selling_office_name": "",
    "co_selling_office_phone": "",
    "list_agent_mui": 15517691,
    "list_agent_direct_work_phone": "(903) 892-3437",
    "list_agent_email": "dixie@deangilbert.com",
    "list_agent_full_name": "Dixie Edwards",
    "list_agent_mls_id": "0200452",
    "co_list_agent_mui": -1,
    "co_list_agent_direct_work_phone": "",
    "co_list_agent_email": "",
    "co_list_agent_full_name": "",
    "co_list_agent_mls_id": "",
    "selling_agent_mui": -1,
    "selling_agent_direct_work_phone": "",
    "selling_agent_email": "",
    "selling_agent_full_name": "",
    "selling_agent_mls_id": "",
    "co_selling_agent_mui": -1,
    "co_selling_agent_direct_work_phone": "",
    "co_selling_agent_email": "",
    "co_selling_agent_full_name": "",
    "co_selling_agent_mls_id": "",
    "listing_agreement": "Exclusive Right to Sell/Lease",
    "possession": "Closing/Funding",
    "capitalization_rate": "",
    "compensation_paid": "",
    "date_available": "",
    "last_status": "Unknown",
    "mls_area_major": "DALLAS NORTH OAK CLIFF (14)",
    "mls_area_minor": "OAKCLIFF (1)",
    "mls": "North Texas Real Estate Information Systems",
    "move_in_date": "",
    "permit_address_internet_yn": true,
    "permit_comments_reviews_yn": true,
    "permit_internet_yn": true,
    "price_change_timestamp": "2016-12-05T12:25:26.263",
    "matrix_modified_dt": "2017-05-31T10:57:52.717",
    "property_association_fees": "",
    "showing_instructions_type": "Go Show-No Appt. Necessary",
    "showing_instructions": "SIGN ON LOT",
    "special_notes": "",
    "tax_legal_description": "TANANGER SPRINGS ADDITION, BLO",
    "total_annual_expenses_include": "",
    "transaction_type": "",
    "virtual_tour_url_branded": "",
    "virtual_tour_url_unbranded": "http://www.propertypanorama.com/instaview/ntreis/12036898",
    "active_option_contract_date": "",
    "keybox_type": "None",
    "keybox_number": "0",
    "close_date": "",
    "close_price": null,
    "back_on_market_date": "",
    "deposit_amount": 0,
    "photo_count": 6,
    "dom": 1334,
    "cdom": 1334,
    "buyers_agency_commission": "3%",
    "sub_agency_commission": "3%",
    "appointment_phone": "",
    "appointment_phone_ext": "",
    "appointment_call": "",
    "owner_name": "Minshew Robert W Trustee",
    "seller_type": "Individual(s)",
    "occupancy": "",
    "private_remarks": ""
  }
}