module.exports = {
  'address': {
    'title': '',
    'subtitle': '',
    'street_name': 'Stanford',
    'city': 'University Park',
    'state': 'Texas',
    'state_code': 'Texas',
    'postal_code': '75225',
    'neighborhood': '',
    'street_suffix': 'Avenue',
    'street_number': '4076',
    'unit_number': '',
    'country': 'United States',
    'country_code': 'USA',
    'matrix_unique_id': 2418967,
    'county_or_parish': 'Dallas',
    'directions': 'North of Lovers, between Preston and Hillcrest',
    'street_dir_prefix': '',
    'street_dir_suffix': '',
    'street_number_searchable': '4076'
  },
  'property': {
    'bedroom_count': 4,
    'bathroom_count': 2.1,
    'half_bathroom_count': 1,
    'full_bathroom_count': 2,
    'description': 'Wonderful University Park 4 bedrm 2.1 bath traditional in coveted Hyer Elementary. Light, bright updated kitchen with 2010 ss appliances. Downstairs master ste. Lovely Formals. Study or 2nd living area could serve as a 5th bedrm or nursery. White tile baths.Spacious 2nd bedrms. Incredible closet space, utility room. Nice backyard & 2car garage. Plantation shutters thru-out. Freshly painted. Impeccably maintained. Terrific offering in the fairway!',
    'square_meters': 250.46451133407658,
    'building_square_meters': 0,
    'lot_square_meters': 0,
    'property_type': 'Residential',
    'property_subtype': 'RES-Single Family',
    'matrix_unique_id': 2418967,
    'year_built': 1962,
    'parking_spaces_covered_total': 2,
    'heating': '{Central Air-Elec,Central Heat-Gas}',
    'flooring': '{Carpet,Ceramic Tile,Wood}',
    'utilities': '{City Sewer,City Water}',
    'utilities_other': '{}',
    'architectural_style': '{Traditional}',
    'structural_style': 'Single Detached',
    'number_of_stories': 2,
    'parking_spaces_garage': 2,
    'number_of_dining_areas': 2,
    'number_of_living_areas': 2,
    'fireplaces_total': 1,
    'lot_number': '3',
    'soil_type': '',
    'construction_materials': 'Brick',
    'construction_materials_walls': '',
    'foundation_details': 'Pier & Beam',
    'roof': 'Composition',
    'pool_yn': false,
    'handicap_yn': false,
    'elementary_school_name': 'Hyer',
    'intermediate_school_name': 'Mcculloch',
    'high_school_name': 'Highland Park',
    'junior_high_school_name': '',
    'middle_school_name': '',
    'primary_school_name': '',
    'senior_high_school_name': '',
    'school_district': 'Highland Park ISD',
    'subdivision_name': 'University Highlands',
    'accessibility_features': '{}',
    'bedroom_bathroom_features': '{}',
    'commercial_features': '{}',
    'community_features': '{}',
    'energysaving_features': '{}',
    'exterior_features': '{}',
    'interior_features': '{Plantation Shutters}',
    'farmranch_features': '{}',
    'fireplace_features': '{}',
    'lot_features': '{Interior Lot}',
    'parking_features': '{Detached,Rear}',
    'pool_features': '{}',
    'security_features': '{}',
    'appliances_yn': false,
    'building_number': '',
    'green_building_certification': '',
    'green_energy_efficient': '',
    'lot_size_dimensions': '50x140',
    'map_coordinates': 'B',
    'pets_yn': false,
    'photo_count': 14,
    'room_count': 13,
    'subdivided_yn': false,
    'surface_rights': '',
    'year_built_details': 'Preowned',
    'zoning': '',
    'security_system_yn': true
  },
  'listing': {
    'currency': 'USD',
    'price': 799000,
    'status': 'Active',
    'matrix_unique_id': 2418967,
    'original_price': 799000,
    'association_fee_frequency': '',
    'association_fee_includes': '',
    'association_type': 'None',
    'mls_number': '11872644',
    'financing_proposed': '',
    'list_date': '2012-12-06T00:00:00.000',
    'list_office_mui': 15504412,
    'list_office_mls_id': 'dpma02',
    'list_office_name': 'Dave Perry-Miller & Associates',
    'list_office_phone': '(214) 526-6600',
    'co_list_office_mui': -1,
    'co_list_office_mls_id': '',
    'co_list_office_name': '',
    'co_list_office_phone': '',
    'selling_office_mui': 15500889,
    'selling_office_mls_id': 'ABAR01',
    'selling_office_name': 'Allie Beth Allman & Assoc.',
    'selling_office_phone': '(214) 521-7355',
    'co_selling_office_mui': -1,
    'co_selling_office_mls_id': '',
    'co_selling_office_name': '',
    'co_selling_office_phone': '',
    'list_agent_mui': 15545246,
    'list_agent_direct_work_phone': '(214) 478-7099',
    'list_agent_email': 'janegordon@daveperrymiller.com',
    'list_agent_full_name': 'Jane Gordon',
    'list_agent_mls_id': '0501125',
    'co_list_agent_mui': -1,
    'co_list_agent_direct_work_phone': '',
    'co_list_agent_email': '',
    'co_list_agent_full_name': '',
    'co_list_agent_mls_id': '',
    'selling_agent_mui': 15559527,
    'selling_agent_direct_work_phone': '(214) 213-8279',
    'selling_agent_email': 'Cgalbraith@sbcglobal.net',
    'selling_agent_full_name': 'Michelene Galbraith',
    'selling_agent_mls_id': '0551417',
    'co_selling_agent_mui': -1,
    'co_selling_agent_direct_work_phone': '',
    'co_selling_agent_email': '',
    'co_selling_agent_full_name': '',
    'co_selling_agent_mls_id': '',
    'listing_agreement': 'Exclusive Right to Sell/Lease',
    'possession': 'Closing/Funding',
    'capitalization_rate': '',
    'compensation_paid': '',
    'date_available': '',
    'last_status': 'Pending',
    'mls_area_major': 'UNIVERSITY PARK/HIGHLAND PARK AREA (25)',
    'mls_area_minor': 'UNIVERSITY PARK/HIGHLAND PARK (5)',
    'mls': 'North Texas Real Estate Information Systems',
    'move_in_date': '',
    'permit_address_internet_yn': true,
    'permit_comments_reviews_yn': false,
    'permit_internet_yn': true,
    'price_change_timestamp': '',
    'matrix_modified_dt': '2016-10-27T14:10:14.807',
    'property_association_fees': '',
    'showing_instructions_type': 'Call-Key Box,Centralized Showing Service',
    'showing_instructions': 'Call CSS - Vacant, on supra',
    'special_notes': '',
    'tax_legal_description': '',
    'total_annual_expenses_include': '',
    'transaction_type': 'For Sale',
    'virtual_tour_url_branded': '',
    'virtual_tour_url_unbranded': '',
    'active_option_contract_date': '',
    'keybox_type': 'Blue iBox',
    'keybox_number': '0',
    'close_date': '2013-02-01T00:00:00.000',
    'close_price': 745000,
    'back_on_market_date': '',
    'deposit_amount': 0,
    'photo_count': 14,
    'dom': 22,
    'cdom': 22,
    'buyers_agency_commission': '3%',
    'sub_agency_commission': '0%',
    'appointment_phone': '(817) 858-0055',
    'appointment_phone_ext': '',
    'appointment_call': 'CSS',
    'owner_name': 'SEE AGENT',
    'seller_type': 'Individual(s)',
    'occupancy': 'Vacant',
    'private_remarks': 'Showings begin Friday, Dec.7th.'
  }
}