module.exports = {
  'board': 'Metrotex Association Of Realtors',
  'email': 'shahedul@24-hourrealty.com',
  'fax': '(214) 570-0087',
  'office_mui': 999888,
  'office_mls_id': '',
  'license_number': '',
  'address': 'Mckinney Avenue',
  'care_of': '',
  'city': 'Dallas',
  'postal_code': '75081',
  'postal_code_plus4': '',
  'state': 'TX',
  'matrix_unique_id': 9999999,
  'matrix_modified_dt': '2017-05-04T12:00:08.333',
  'mls': 'North Texas Real Estate Information Systems',
  'mls_id': 'RCHT01',
  'mls_provider': 'Metrotex Association Of Realtors',
  'nar_number': '',
  'contact_mui': '',
  'contact_mls_id': '',
  'long_name': 'Rechat RealTor Success Console',
  'name': 'Rechat',
  'status': 'Active',
  'phone': '(214) 999-9999',
  'other_phone': '',
  'st_address': '811 S. Central Expy Suite 300G',
  'st_city': 'Richardson',
  'st_country': '',
  'st_postal_code': '75080',
  'st_postal_code_plus4': '',
  'st_state': 'TX',
  'url': 'www.rechat.com'
}