const attachCalendarEvents = require('../Calendar/events')
const attachContactEvents = require('../Contact/events')
const attachContactEmailEvents = require('../Contact/email/events')
const attachFlowEvents = require('../Flow/events')
const attachShowingEvents = require('../Showing/showing/events')
const attachTaskEventHandler = require('../CRM/Task/events')
const attachTouchEventHandler = require('../CRM/Touch/events')
const attachCalIntEventHandler = require('../CalendarIntegration/events')
const attachContactIntEventHandler = require('../ContactIntegration/events')
const attachBrandTriggerEventHandler = require('../Trigger/brand_trigger/events')
const attachTriggerEventHandler = require('../Trigger/events')
const attachGoogleEventHandlers = require('../Google/credential/events')
const attachMicrosoftEventHandlers = require('../Microsoft/credential/events')

module.exports = function() {
  attachCalendarEvents()
  attachContactEvents()
  attachContactEmailEvents()
  attachFlowEvents()
  attachShowingEvents()
  attachTaskEventHandler()
  attachTouchEventHandler()
  attachCalIntEventHandler()
  attachContactIntEventHandler()
  attachBrandTriggerEventHandler()
  attachTriggerEventHandler()
  attachGoogleEventHandlers()
  attachMicrosoftEventHandlers()
}
