const _ = require('lodash')
const sq = require('../../../lib/utils/squel_extensions')

const contexts = [
  {
    key: 'photo',
    label: 'Photo',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: null,
    optional: null,
    triggers_brokerwolf: false,
    order: 0
  },
  {
    key: 'list_date',
    label: 'Listing Start Date',
    short_label: 'Lst',
    section: 'Dates',
    needs_approval: true,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Date',
    format: null,
    required: sq.SqArray.from([
      'Selling',
      'Resale',
      'New Home',
      'Lot / Land',
      'Commercial Sale'
    ]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 1
  },
  {
    key: 'expiration_date',
    label: 'Listing Expiration',
    short_label: 'Exp',
    section: 'Dates',
    needs_approval: true,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Date',
    format: null,
    required: sq.SqArray.from([
      'Selling',
      'Resale',
      'New Home',
      'Lot / Land',
      'Commercial Sale'
    ]),
    optional: sq.SqArray.from([
      'Commercial Sale',
      'Lot / Land',
      'New Home',
      'Resale',
      'Selling'
    ]),
    triggers_brokerwolf: false,
    order: 2
  },
  {
    key: 'contract_date',
    label: 'Executed Date',
    short_label: 'Off',
    section: 'Dates',
    needs_approval: true,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Date',
    format: null,
    required: sq.SqArray.from(['Buying', 'Resale', 'New Home', 'Lot / Land', 'Commercial Sale']),
    optional: sq.SqArray.from([
      'Active Offer',
      'Buying',
      'Commercial Sale',
      'Lot / Land',
      'New Home',
      'Resale',
      'Selling'
    ]),
    triggers_brokerwolf: false,
    order: 3
  },
  {
    key: 'inspection_date',
    label: 'Inspection Date',
    short_label: 'Ins',
    section: 'Dates',
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Date',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([
      'Active Offer',
      'Buying',
      'Commercial Sale',
      'Lot / Land',
      'New Home',
      'Resale',
      'Selling'
    ]),
    triggers_brokerwolf: false,
    order: 4
  },
  {
    key: 'option_period',
    label: 'End Of Option',
    short_label: 'Opt',
    section: 'Dates',
    needs_approval: true,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Date',
    format: null,
    required: sq.SqArray.from(['Buying', 'Resale', 'New Home', 'Lot / Land', 'Commercial Sale']),
    optional: sq.SqArray.from([
      'Active Offer',
      'Buying',
      'Commercial Sale',
      'Lot / Land',
      'New Home',
      'Resale',
      'Selling'
    ]),
    triggers_brokerwolf: false,
    order: 5
  },
  {
    key: 'financing_due',
    label: 'Financing Due',
    short_label: 'Fin',
    section: 'Dates',
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Date',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from(['Buying', 'Commercial Sale', 'Lot / Land', 'New Home', 'Resale']),
    triggers_brokerwolf: false,
    order: 6
  },
  {
    key: 'title_due',
    label: 'Title Due',
    short_label: 'Til',
    section: 'Dates',
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Date',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from(['Buying', 'Commercial Sale', 'Lot / Land', 'New Home', 'Resale']),
    triggers_brokerwolf: false,
    order: 7
  },
  {
    key: 't47_due',
    label: 'Survey Due',
    short_label: 'T47',
    section: 'Dates',
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Date',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from(['Buying', 'Commercial Sale', 'Lot / Land', 'New Home', 'Resale']),
    triggers_brokerwolf: false,
    order: 8
  },
  {
    key: 'closing_date',
    label: 'Closing Date',
    short_label: 'Cls',
    section: 'Dates',
    needs_approval: true,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Date',
    format: null,
    required: sq.SqArray.from(['Buying', 'Resale', 'New Home', 'Lot / Land', 'Commercial Sale']),
    optional: sq.SqArray.from([
      'Active Offer',
      'Buying',
      'Commercial Sale',
      'Lot / Land',
      'New Home',
      'Resale',
      'Selling'
    ]),
    triggers_brokerwolf: false,
    order: 9
  },
  {
    key: 'possession_date',
    label: 'Possession Date',
    short_label: 'Pos',
    section: 'Dates',
    needs_approval: true,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Date',
    format: null,
    required: sq.SqArray.from(['Buying', 'Resale', 'New Home', 'Lot / Land', 'Commercial Sale']),
    optional: sq.SqArray.from([
      'Active Offer',
      'Buying',
      'Commercial Sale',
      'Lot / Land',
      'New Home',
      'Resale',
      'Selling'
    ]),
    triggers_brokerwolf: false,
    order: 10
  },
  {
    key: 'list_price',
    label: 'List Price',
    short_label: null,
    section: 'Listing',
    needs_approval: true,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Number',
    format: 'Currency',
    required: sq.SqArray.from([
      'Selling',
      'Resale',
      'New Home',
      'Lot / Land',
      'Commercial Sale'
    ]),
    optional: sq.SqArray.from([
      'Buying',
      'Commercial Sale',
      'Lot / Land',
      'New Home',
      'Resale',
      'Selling'
    ]),
    triggers_brokerwolf: false,
    order: 11
  },
  {
    key: 'sales_price',
    label: 'Sales Price',
    short_label: null,
    section: 'CDA',
    needs_approval: true,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Number',
    format: 'Currency',
    required: sq.SqArray.from(['Buying', 'Resale', 'New Home', 'Lot / Land', 'Commercial Sale']),
    optional: sq.SqArray.from([
      'Active Offer',
      'Buying',
      'Commercial Sale',
      'Lot / Land',
      'New Home',
      'Resale',
      'Selling'
    ]),
    triggers_brokerwolf: false,
    order: 12
  },
  {
    key: 'leased_price',
    label: 'Leased Price',
    short_label: null,
    section: 'CDA',
    needs_approval: true,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Number',
    format: 'Currency',
    required: sq.SqArray.from(['Buying', 'Residential Lease', 'Commercial Lease']),
    optional: sq.SqArray.from([
      'Active Offer',
      'Buying',
      'Commercial Lease',
      'Residential Lease',
      'Selling'
    ]),
    triggers_brokerwolf: false,
    order: 13
  },
  {
    key: 'full_address',
    label: 'Full Address',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'MLS',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 14
  },
  {
    key: 'legal_description',
    label: 'Legal Description',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 15
  },
  {
    key: 'unit_number',
    label: 'Unit Numbers',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'MLS',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 16
  },
  {
    key: 'building_number',
    label: 'Building Numbers',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 17
  },
  {
    key: 'project_name',
    label: 'Project Name',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 18
  },
  {
    key: 'lot_number',
    label: 'Lot Number',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 19
  },
  {
    key: 'block_number',
    label: 'Block Number',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 20
  },
  {
    key: 'subdivision',
    label: 'Subdivision',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 21
  },
  {
    key: 'street_number',
    label: 'Street Number',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'MLS',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 22
  },
  {
    key: 'street_dir_prefix',
    label: 'Street Dir Prefix',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'MLS',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 23
  },
  {
    key: 'street_name',
    label: 'Street Name',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'MLS',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 24
  },
  {
    key: 'street_suffix',
    label: 'Street Suffix',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'MLS',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 25
  },
  {
    key: 'street_address',
    label: 'Street Address',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'MLS',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 26
  },
  {
    key: 'city',
    label: 'City',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'MLS',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 27
  },
  {
    key: 'state',
    label: 'State',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'MLS',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 28
  },
  {
    key: 'state_code',
    label: 'State Code',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'MLS',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 29
  },
  {
    key: 'postal_code',
    label: 'Postal Code',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'MLS',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 30
  },
  {
    key: 'county',
    label: 'County',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'MLS',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 31
  },
  {
    key: 'year_built',
    label: 'Year Built',
    short_label: null,
    section: 'Listing',
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Number',
    format: null,
    required: sq.SqArray.from(['Selling', 'Buying', 'Resale', 'New Home', 'Residential Lease']),
    optional: sq.SqArray.from(['Buying', 'Commercial Lease', 'Commercial Sale', 'Selling']),
    triggers_brokerwolf: false,
    order: 32
  },
  {
    key: 'listing_status',
    label: 'Status',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 33
  },
  {
    key: 'mls_number',
    label: 'MLS#',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Number',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from(['Buying', 'Selling']),
    triggers_brokerwolf: false,
    order: 34
  },
  {
    key: 'mls_area_major',
    label: 'MLS Major Area',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 35
  },
  {
    key: 'mls_area_minor',
    label: 'MLS Minor Area',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 36
  },
  {
    key: 'file_id',
    label: 'File ID (Admin use)',
    short_label: null,
    section: 'Listing',
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Number',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([
      'Buying',
      'Commercial Lease',
      'Commercial Sale',
      'Lot / Land',
      'New Home',
      'Resale',
      'Residential Lease',
      'Selling'
    ]),
    triggers_brokerwolf: false,
    order: 37
  },
  {
    key: 'commission_listing',
    label: 'Commission Listing',
    short_label: null,
    section: null,
    needs_approval: true,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Number',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 38
  },
  {
    key: 'commission_selling',
    label: 'Commission Selling',
    short_label: null,
    section: null,
    needs_approval: true,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Number',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 39
  },
  {
    key: 'property_type',
    label: 'Property Type',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 40
  },
  {
    key: 'square_meters',
    label: 'Square Meters',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Number',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 41
  },
  {
    key: 'lease_price',
    label: 'Original Lease',
    short_label: null,
    section: 'Listing',
    needs_approval: true,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Number',
    format: 'Currency',
    required: sq.SqArray.from(['Selling', 'Residential Lease', 'Commercial Lease']),
    optional: sq.SqArray.from(['Buying', 'Commercial Lease', 'Residential Lease']),
    triggers_brokerwolf: false,
    order: 42
  },
  {
    key: 'lease_executed',
    label: 'Lease Executed',
    short_label: null,
    section: 'Dates',
    needs_approval: true,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Date',
    format: null,
    required: sq.SqArray.from(['Buying', 'Residential Lease', 'Commercial Lease']),
    optional: sq.SqArray.from([
      'Active Offer',
      'Buying',
      'Commercial Lease',
      'Residential Lease',
      'Selling'
    ]),
    triggers_brokerwolf: false,
    order: 43
  },
  {
    key: 'lease_application_date',
    label: 'Lease Application Date',
    short_label: null,
    section: 'Dates',
    needs_approval: true,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Date',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from(['Buying', 'Commercial Lease', 'Residential Lease']),
    triggers_brokerwolf: false,
    order: 44
  },
  {
    key: 'lease_begin',
    label: 'Lease Begin',
    short_label: null,
    section: 'Dates',
    needs_approval: true,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Date',
    format: null,
    required: sq.SqArray.from(['Buying', 'Residential Lease', 'Commercial Lease']),
    optional: sq.SqArray.from([
      'Active Offer',
      'Buying',
      'Commercial Lease',
      'Residential Lease',
      'Selling'
    ]),
    triggers_brokerwolf: false,
    order: 45
  },
  {
    key: 'lease_end',
    label: 'Lease End',
    short_label: null,
    section: 'Dates',
    needs_approval: true,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Date',
    format: null,
    required: sq.SqArray.from(['Buying', 'Residential Lease', 'Commercial Lease']),
    optional: sq.SqArray.from([
      'Active Offer',
      'Buying',
      'Commercial Lease',
      'Residential Lease',
      'Selling'
    ]),
    triggers_brokerwolf: false,
    order: 46
  },
  {
    key: 'title_company',
    label: 'Title Company',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 47
  },
  {
    key: 'ender_type',
    label: 'Ender Type',
    short_label: null,
    section: null,
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from([]),
    triggers_brokerwolf: false,
    order: 48
  },
  {
    key: '12a1b',
    label: 'Seller\'s Credit 12A(1)(b)',
    short_label: null,
    section: 'CDA',
    needs_approval: true,
    exports: true,
    preffered_source: 'Provided',
    default_value: '0',
    data_type: 'Number',
    format: 'Currency',
    required: sq.SqArray.from(['Buying', 'Resale', 'New Home', 'Lot / Land', 'Commercial Sale']),
    optional: sq.SqArray.from([
      'Buying',
      'Commercial Sale',
      'Lot / Land',
      'New Home',
      'Resale',
      'Selling',
      'Active Offer'
    ]),
    triggers_brokerwolf: false,
    order: 49
  },
  {
    key: 'charitable_donations',
    label: 'Charitable donations',
    short_label: null,
    section: 'CDA',
    needs_approval: true,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Number',
    format: 'Currency',
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from(['Buying', 'Commercial Sale', 'Lot / Land', 'New Home', 'Resale']),
    triggers_brokerwolf: false,
    order: 50
  },
  {
    key: 'ranch_name',
    label: 'Ranch name',
    short_label: null,
    section: 'CDA',
    needs_approval: null,
    exports: true,
    preffered_source: 'Provided',
    default_value: null,
    data_type: 'Text',
    format: null,
    required: sq.SqArray.from([]),
    optional: sq.SqArray.from(['Lot / Land', 'Selling']),
    triggers_brokerwolf: false,
    order: 51
  }
]

module.exports = _.keyBy(contexts, 'key')
