INSERT INTO properties (
  property_type,
  property_subtype,
  bedroom_count,
  bathroom_count,
  address_id,
  matrix_unique_id,
  description,
  square_meters,
  lot_square_meters,
  year_built,
  parking_spaces_covered_total,
  exterior_features,
  interior_features,
  fireplace_features,
  lot_features,
  parking_features,
  pool_features,
  security_features,
  half_bathroom_count,
  full_bathroom_count,
  heating,
  flooring,
  utilities,
  utilities_other,
  architectural_style,
  number_of_stories,
  number_of_parking_spaces,
  garage_length,
  garage_width,
  number_of_dining_areas,
  number_of_living_areas,
  fireplaces_total,
  lot_number,
  soil_type,
  construction_materials,
  foundation_details,
  roof,
  pool_yn,
  handicap_yn,
  elementary_school_name,
  intermediate_school_name,
  high_school_Name,
  junior_high_school_name,
  middle_school_name,
  primary_school_name,
  senior_high_school_name,
  school_district,
  subdivision_name,
  appliances_yn,
  green_building_certification,
  green_energy_efficient,
  lot_size,
  lot_size_area,
  lot_size_dimensions,
  number_of_pets_allowed,
  number_of_units,
  pets_yn,
  furnished_yn,
  fenced_yard_yn,
  block,
  mls
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20,
  $21,
  $22,
  $23,
  $24,
  $25,
  $26,
  $27,
  $28,
  $29,
  $30,
  $31,
  $32,
  $33,
  $34,
  $35,
  $36,
  $37,
  $38,
  $39,
  $40,
  $41,
  $42,
  $43,
  $44,
  $45,
  $46,
  $47,
  $48,
  $49,
  $50,
  $51,
  $52,
  $53,
  $54,
  $55,
  $56,
  $57,
  $58,
  $59,
  $60,
  $61::mls
)

ON CONFLICT (matrix_unique_id, mls) DO UPDATE SET
  property_type = $1,
  property_subtype = $2,
  bedroom_count = $3,
  bathroom_count = $4,
  description = $7,
  square_meters = $8,
  lot_square_meters = $9,
  year_built = $10,
  parking_spaces_covered_total = $11,
  exterior_features = $12,
  interior_features = $13,
  fireplace_features = $14,
  lot_features = $15,
  parking_features = $16,
  pool_features = $17,
  security_features = $18,
  half_bathroom_count = $19,
  full_bathroom_count = $20,
  heating = $21,
  flooring = $22,
  utilities = $23,
  utilities_other = $24,
  architectural_style = $25,
  number_of_stories = $26,
  number_of_parking_spaces = $27,
  garage_length = $28,
  garage_width = $29,
  number_of_dining_areas = $30,
  number_of_living_areas = $31,
  fireplaces_total = $32,
  lot_number = $33,
  soil_type = $34,
  construction_materials = $35,
  foundation_details = $36,
  roof = $37,
  pool_yn = $38,
  handicap_yn = $39,
  elementary_school_name = $40,
  intermediate_school_name = $41,
  high_school_Name = $42,
  junior_high_school_name = $43,
  middle_school_name = $44,
  primary_school_name = $45,
  senior_high_school_name = $46,
  school_district = $47,
  subdivision_name = $48,
  appliances_yn = $49,
  green_building_certification = $50,
  green_energy_efficient = $51,
  lot_size = $52,
  lot_size_area = $53,
  lot_size_dimensions = $54,
  number_of_pets_allowed = $55,
  number_of_units = $56,
  pets_yn = $57,
  furnished_yn = $58,
  fenced_yard_yn = $59,
  block = $60,
  updated_at = CLOCK_TIMESTAMP(),
  pets_policy = $62,
  amenities = $63

WHERE properties.matrix_unique_id = $6 AND properties.mls = $61::mls

RETURNING id
