INSERT INTO showings
    (
        agent,
        remote_id,
        mls_number,
        mls_title,
        date_raw,
        start_date,
        end_date,
        remote_agent_name,
        remote_agent_email,
        remote_agent_desc,
        remote_agent_phone_office,
        remote_agent_phone_cell,
        result,
        feedback_text,
        cancellation_reason,
        note_text
    )
VALUES
    (
      $1,
      $2,
      $3,
      $4,
      $5,
      $6,
      $7,
      $8,
      $9,
      $10,
      $11,
      $12,
      $13,
      $14,
      $15,
      $16
    )
RETURNING id
