INSERT INTO showings
    (
        agent,
        mls_number,
        mls_title,
        showing_start_date,
        showing_end_date,
        remote_agent_id,
        remote_agent_name,
        remote_agent_email,
        remote_agent_desc,
        remote_agent_phone_office,
        remote_agent_phone_cell,
        result,
        feedback_text,
        feedback_id,
        cancellation_reason,
        note_text,
        note_id
    )
VALUES
    (
      $1,
      $2,
      $3,
      $4,
      $5,
      $6,
      $7,
      $8,
      $9,
      $10,
      $11,
      $12,
      $13,
      $14,
      $15,
      $16,
      $17
    )
RETURNING id
