INSERT INTO showinghub.showable_listings (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL,
  listing_id text NOT NULL,
  created_on timestamp NOT NULL,
  upi text,
  address1 text,
  city text,
  state text,
  zip_code text,
  list_agent_mls_id text,
  list_agent_name text,
  list_agent_license_state_affirmation boolean,
  list_agent_license_number text,
  list_agent_license_state text,
  showable_start_date timestamp not null,
  showable_end_date timestamp,
  showing_instructions text,
  required_participants showinghub_required_participant NOT NULL,
  showing_method showinghub_showing_method NOT NULL,
  confirmation_type showinghub_confirmation_method NOT NULL,
  showings_allowed showinghub_showing_status NOT NULL
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20,
  $21
)