module.exports.CREATE_EVENT = 'email_campaign:create'
module.exports.SEND_EVENT = 'email_campaign:send'
module.exports.DELETE_EVENT = 'email_campaign:delete'
module.exports.STATS_EVENT = 'email_campaign:stats'
module.exports.FAIL_EVENT = 'email_campaign:fail'
