INSERT INTO listings (
  property_id,
  price,
  status,
  matrix_unique_id,
  original_price,
  last_price,
  association_fee,
  association_fee_frequency,
  association_fee_includes,
  mls_number,
  unexempt_taxes,
  financing_proposed,
  list_office_mui,
  list_office_mls_id,
  list_office_name,
  list_office_phone,
  co_list_office_mui,
  co_list_office_mls_id,
  co_list_office_name,
  co_list_office_phone,
  selling_office_mui,
  selling_office_mls_id,
  selling_office_name,
  selling_office_phone,
  co_selling_office_mui,
  co_selling_office_mls_id,
  co_selling_office_name,
  co_selling_office_phone,
  list_agent_mui,
  list_agent_direct_work_phone,
  list_agent_email,
  list_agent_full_name,
  list_agent_mls_id,
  co_list_agent_mui,
  co_list_agent_direct_work_phone,
  co_list_agent_email,
  co_list_agent_full_name,
  co_list_agent_mls_id,
  selling_agent_mui,
  selling_agent_direct_work_phone,
  selling_agent_email,
  selling_agent_full_name,
  selling_agent_mls_id,
  co_selling_agent_mui,
  co_selling_agent_direct_work_phone,
  co_selling_agent_email,
  co_selling_agent_full_name,
  co_selling_agent_mls_id,
  listing_agreement,
  possession,
  mls_area_major,
  mls_area_minor,
  mls_name,
  matrix_modified_dt,
  showing_instructions_type,
  tax_legal_description,
  keybox_type,
  keybox_number,
  close_date,
  close_price,
  dom,
  cdom,
  buyers_agency_commission,
  sub_agency_commission,
  list_date,
  showing_instructions,
  appointment_phone,
  appointment_phone_ext,
  appointment_call,
  occupancy,
  private_remarks,
  application_fee_yn,
  mls,
  revision,
  original_mls_property_type,
  original_mls_property_subtype,
  original_mls_status,
  transaction_type,
  usage_type,
  structure_type,
  is_address_public,
  parcel_number,
  public_display,
  annual_tax,
  virtual_tour,
  sub_agency_offered,
  transaction_broker_commission,
  compensation_based_on
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20,
  $21,
  $22,
  $23,
  $24,
  $25,
  $26,
  $27,
  $28,
  $29,
  $30,
  $31,
  $32,
  $33,
  $34,
  $35,
  $36,
  $37,
  $38,
  $39,
  $40,
  $41,
  $42,
  $43,
  $44,
  $45,
  $46,
  $47,
  $48,
  $49,
  $50,
  $51,
  $52,
  $53,
  CASE WHEN $54 = '' THEN NULL ELSE $54::timestamptz END,
  $55,
  $56,
  $57,
  $58,
  CASE WHEN $59 = '' THEN NULL ELSE $59::timestamptz END,
  $60,
  $61,
  $62,
  $63,
  $64,
  CASE WHEN $65 = '' THEN NULL ELSE $65::timestamptz END,
  $66,
  $67,
  $68,
  $69,
  $70,
  $71,
  $72,
  $73::mls,
  $74,
  $75,
  $76,
  $77,
  $78,
  $79,
  $80,
  $81,
  $82,
  $83,
  $84,
  $85,
  $86,
  $87,
  $88
)

ON CONFLICT (matrix_unique_id, mls) DO UPDATE SET
  price = $2,
  status = $3,
  original_price = $5,
  last_price = $6,
  association_fee = $7,
  association_fee_frequency = $8,
  association_fee_includes = $9,
  mls_number = $10,
  unexempt_taxes = $11,
  financing_proposed = $12,
  list_office_mui = $13,
  list_office_mls_id = $14,
  list_office_name = $15,
  list_office_phone = $16,
  co_list_office_mui = $17,
  co_list_office_mls_id = $18,
  co_list_office_name = $19,
  co_list_office_phone = $20,
  selling_office_mui = $21,
  selling_office_mls_id = $22,
  selling_office_name = $23,
  selling_office_phone = $24,
  co_selling_office_mui = $25,
  co_selling_office_mls_id = $26,
  co_selling_office_name = $27,
  co_selling_office_phone = $28,
  list_agent_mui = $29,
  list_agent_direct_work_phone = $30,
  list_agent_email = $31,
  list_agent_full_name = $32,
  list_agent_mls_id = $33,
  co_list_agent_mui = $34,
  co_list_agent_direct_work_phone = $35,
  co_list_agent_email = $36,
  co_list_agent_full_name = $37,
  co_list_agent_mls_id = $38,
  selling_agent_mui = $39,
  selling_agent_direct_work_phone = $40,
  selling_agent_email = $41,
  selling_agent_full_name = $42,
  selling_agent_mls_id = $43,
  co_selling_agent_mui = $44,
  co_selling_agent_direct_work_phone = $45,
  co_selling_agent_email = $46,
  co_selling_agent_full_name = $47,
  co_selling_agent_mls_id = $48,
  listing_agreement = $39,
  possession = $50,
  mls_area_major = $51,
  mls_area_minor = $52,
  mls_name = $53,
  matrix_modified_dt = CASE WHEN $54 = '' THEN NULL ELSE $54::timestamptz END,
  showing_instructions_type = $55,
  tax_legal_description = $56,
  keybox_type = $57,
  keybox_number = $58,
  close_date = CASE WHEN $59 = '' THEN NULL ELSE $59::timestamptz END,
  close_price = $60,
  dom = $61,
  cdom = $62,
  buyers_agency_commission = $63,
  sub_agency_commission = $64,
  list_date = CASE WHEN $65 = '' THEN NULL ELSE $65::timestamptz END,
  showing_instructions = $66,
  appointment_phone = $67,
  appointment_phone_ext = $68,
  appointment_call = $69,
  occupancy = $70,
  private_remarks = $71,
  application_fee_yn = $72,
  revision = $74,
  is_address_public = $81,
  parcel_number = $82,
  public_display = $83,
  annual_tax = $84,
  virtual_tour = $85,
  sub_agency_offered = $86,
  transaction_broker_commission = $87,
  compensation_based_on = $88,
  updated_at = CLOCK_TIMESTAMP(),
  deleted_at = NULL

WHERE listings.matrix_unique_id = $4 AND listings.mls = $73::mls

RETURNING id
