INSERT INTO listings (
  property_id,
  alerting_agent_id,
  listing_agent_id,
  currency,
  price,
  status,
  matrix_unique_id,
  original_price,
  last_price,
  low_price,
  association_fee,
  association_fee_frequency,
  association_fee_includes,
  association_type,
  mls_number,
  unexempt_taxes,
  financing_proposed,
  list_office_mui,
  list_office_mls_id,
  list_office_name,
  list_office_phone,
  co_list_office_mui,
  co_list_office_mls_id,
  co_list_office_name,
  co_list_office_phone,
  selling_office_mui,
  selling_office_mls_id,
  selling_office_name,
  selling_office_phone,
  co_selling_office_mui,
  co_selling_office_mls_id,
  co_selling_office_name,
  co_selling_office_phone,
  list_agent_mui,
  list_agent_direct_work_phone,
  list_agent_email,
  list_agent_full_name,
  list_agent_mls_id,
  co_list_agent_mui,
  co_list_agent_direct_work_phone,
  co_list_agent_email,
  co_list_agent_full_name,
  co_list_agent_mls_id,
  selling_agent_mui,
  selling_agent_direct_work_phone,
  selling_agent_email,
  selling_agent_full_name,
  selling_agent_mls_id,
  co_selling_agent_mui,
  co_selling_agent_direct_work_phone,
  co_selling_agent_email,
  co_selling_agent_full_name,
  co_selling_agent_mls_id,
  listing_agreement,
  possession,
  capitalization_rate,
  compensation_paid,
  date_available,
  last_status,
  mls_area_major,
  mls_area_minor,
  mls,
  move_in_date,
  permit_address_internet_yn,
  permit_comments_reviews_yn,
  permit_internet_yn,
  price_change_timestamp,
  matrix_modified_dt,
  property_association_fees,
  showing_instructions_type,
  special_notes,
  tax_legal_description,
  total_annual_expenses_include,
  transaction_type,
  virtual_tour_url_branded,
  virtual_tour_url_unbranded,
  active_option_contract_date,
  keybox_type,
  keybox_number,
  close_date,
  close_price,
  back_on_market_date,
  deposit_amount,
  dom,
  cdom,
  buyers_agency_commission,
  sub_agency_commission,
  list_date,
  showing_instructions,
  appointment_phone,
  appointment_phone_ext,
  appointment_call,
  owner_name,
  seller_type,
  occupancy,
  private_remarks
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20,
  $21,
  $22,
  $23,
  $24,
  $25,
  $26,
  $27,
  $28,
  $29,
  $30,
  $31,
  $32,
  $33,
  $34,
  $35,
  $36,
  $37,
  $38,
  $39,
  $40,
  $41,
  $42,
  $43,
  $44,
  $45,
  $46,
  $47,
  $48,
  $49,
  $50,
  $51,
  $52,
  $53,
  $54,
  $55,
  $56,
  $57,
  $58,
  $59,
  $60,
  $61,
  $62,
  $63,
  $64,
  $65,
  $66,
  CASE WHEN $67 = '' THEN NULL ELSE $67::timestamptz END,
  CASE WHEN $68 = '' THEN NULL ELSE $68::timestamptz END,
  $69,
  $70,
  $71,
  $72,
  $73,
  $74,
  $75,
  $76,
  $77,
  $78,
  $79,
  CASE WHEN $80 = '' THEN NULL ELSE $80::timestamptz END,
  $81,
  $82,
  $83,
  $84,
  $85,
  $86,
  $87,
  CASE WHEN $88 = '' THEN NULL ELSE $88::timestamptz END,
  $89,
  $90,
  $91,
  $92,
  $93,
  $94,
  $95,
  $96
)

ON CONFLICT (matrix_unique_id) DO UPDATE SET
  alerting_agent_id = $2,
  listing_agent_id = $3,
  currency = $4,
  price = $5,
  status = $6,
  original_price = $8,
  last_price = $9,
  low_price = $10,
  association_fee = $11,
  association_fee_frequency = $12,
  association_fee_includes = $13,
  association_type = $14,
  mls_number = $15,
  unexempt_taxes = $16,
  financing_proposed = $17,
  list_office_mui = $18,
  list_office_mls_id = $19,
  list_office_name = $20,
  list_office_phone = $21,
  co_list_office_mui = $22,
  co_list_office_mls_id = $23,
  co_list_office_name = $24,
  co_list_office_phone = $25,
  selling_office_mui = $26,
  selling_office_mls_id = $27,
  selling_office_name = $28,
  selling_office_phone = $29,
  co_selling_office_mui = $30,
  co_selling_office_mls_id = $31,
  co_selling_office_name = $32,
  co_selling_office_phone = $33,
  list_agent_mui = $34,
  list_agent_direct_work_phone = $35,
  list_agent_email = $36,
  list_agent_full_name = $37,
  list_agent_mls_id = $38,
  co_list_agent_mui = $39,
  co_list_agent_direct_work_phone = $40,
  co_list_agent_email = $41,
  co_list_agent_full_name = $42,
  co_list_agent_mls_id = $43,
  selling_agent_mui = $44,
  selling_agent_direct_work_phone = $45,
  selling_agent_email = $46,
  selling_agent_full_name = $47,
  selling_agent_mls_id = $48,
  co_selling_agent_mui = $49,
  co_selling_agent_direct_work_phone = $50,
  co_selling_agent_email = $51,
  co_selling_agent_full_name = $52,
  co_selling_agent_mls_id = $53,
  listing_agreement = $54,
  possession = $55,
  capitalization_rate = $56,
  compensation_paid = $57,
  date_available = $58,
  last_status = $59,
  mls_area_major = $60,
  mls_area_minor = $61,
  mls = $62,
  move_in_date = $63,
  permit_address_internet_yn = $64,
  permit_comments_reviews_yn = $65,
  permit_internet_yn = $66,
  price_change_timestamp = CASE WHEN $67 = '' THEN NULL ELSE $67::timestamptz END,
  matrix_modified_dt = CASE WHEN $68 = '' THEN NULL ELSE $68::timestamptz END,
  property_association_fees = $69,
  showing_instructions_type = $70,
  special_notes = $71,
  tax_legal_description = $72,
  total_annual_expenses_include = $73,
  transaction_type = $74,
  virtual_tour_url_branded = $75,
  virtual_tour_url_unbranded = $76,
  active_option_contract_date = $77,
  keybox_type = $78,
  keybox_number = $79,
  close_date = CASE WHEN $80 = '' THEN NULL ELSE $80::timestamptz END,
  close_price = $81,
  back_on_market_date = $82,
  deposit_amount = $83,
  dom = $84,
  cdom = $85,
  buyers_agency_commission = $86,
  sub_agency_commission = $87,
  list_date = CASE WHEN $88 = '' THEN NULL ELSE $88::timestamptz END,
  showing_instructions = $89,
  appointment_phone = $90,
  appointment_phone_ext = $91,
  appointment_call = $92,
  owner_name = $93,
  seller_type = $94,
  occupancy = $95,
  private_remarks = $96

WHERE listings.matrix_unique_id = $7

RETURNING id
