const attachCalendarEvents = require('../../lib/models/Calendar/events')
const attachContactEvents = require('../../lib/models/Contact/events')
const attachContactEmailEvents = require('../../lib/models/Contact/email/events')
const attachFlowEvents = require('../../lib/models/Flow/events')
const attachShowingEvents = require('../../lib/models/Showing/showing/events')
const attachTaskEventHandler = require('../../lib/models/CRM/Task/events')
const attachTouchEventHandler = require('../../lib/models/CRM/Touch/events')
const attachCalIntEventHandler = require('../../lib/models/CalendarIntegration/events')
const attachContactIntEventHandler = require('../../lib/models/ContactIntegration/events')
const attachBrandTriggerEventHandler = require('../../lib/models/Trigger/brand_trigger/events')
const attachTriggerEventHandler = require('../../lib/models/Trigger/events')

module.exports = function() {
  attachCalendarEvents()
  attachContactEvents()
  attachContactEmailEvents()
  attachFlowEvents()
  attachShowingEvents()
  attachTaskEventHandler()
  attachTouchEventHandler()
  attachCalIntEventHandler()
  attachContactIntEventHandler()
  attachBrandTriggerEventHandler()
  attachTriggerEventHandler()
}
