export type MarketingPalette = Partial<{
  'body-bg-color': string
  'body-text-color': string
  'body-font-family': string
  'body-font-size': string
  'body-font-weight': string
  'body-logo-wide': string
  'body-logo-square': string
  'container-bg-color': string
  'container-text-color': string
  'container-font-family': string
  'container-font-size': string
  'container-font-weight': string
  'container-logo-wide': string
  'container-logo-square': string
  'button-bg-color': string
  'button-text-color': string
  'button-font-family': string
  'button-font-size': string
  'button-font-weight': string
  'button-border': string
  'light-text-color': string
  'light-font-family': string
  'light-font-size': string
  'light-font-weight': string
  'h1-text-color': string
  'h1-font-family': string
  'h1-font-size': string
  'h1-font-weight': string
  'h2-text-color': string
  'h2-font-family': string
  'h2-font-size': string
  'h2-font-weight': string
  'h3-text-color': string
  'h3-font-family': string
  'h3-font-size': string
  'h3-font-weight': string
  'inverted-button-bg-color': string
  'inverted-button-text-color': string
  'inverted-light-text-color': string
  'inverted-h1-text-color': string
  'inverted-h2-text-color': string
  'inverted-h3-text-color': string
  'inverted-logo-wide': string
  'inverted-logo-square': string
  'inverted-container-bg-color': string
  'inverted-container-text-color': string
  website: string
  name: string
  phone_number: string
}>
