INSERT INTO google_calendar_events
  (
    google_credential,
    google_calendar,
    event_id,
    description,
    summary,
    location,
    color_id,
    ical_uid,
    transparency,
    visibility,
    hangout_link,
    html_link,
    status,
    sequence,
    anyone_can_add_self,
    guests_can_invite_others,
    guests_can_modify,
    guests_can_see_other_guests,
    attendees_omitted,
    locked,
    private_copy,
    creator,
    organizer,
    attendees,
    attachments,
    conference_data,
    extended_properties,
    gadget,
    reminders,
    source,
    created,
    updated,
    event_start,
    event_end,
    end_time_unspecified,
    recurrence,
    recurring_eventId,
    original_start_time,
    origin
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26,
    $27,
    $28,
    $29,
    $30,
    $31,
    $32,
    $33,
    $34,
    $35,
    $36,
    $37,
    $38,
    $39
  )
ON CONFLICT (google_credential, google_calendar, event_id) DO UPDATE SET
  description = $1,
  summary = $2,,
  location = $3,
  color_id = $4,
  ical_uid = $5,
  transparency = $6,
  visibility = $7,
  hangout_link = $8,
  html_link = $9,
  status = $10,
  sequence = $11,
  anyone_can_add_self = $12,
  guests_can_invite_others = $13,
  guests_can_modify = $14,
  guests_can_see_other_guests = $15,
  attendees_omitted = $16,
  locked = $17,
  private_copy = $18,
  creator = $19,
  organizer = $20,
  attendees = $21,
  attachments = $22,
  conference_data = $23,
  extended_properties = $24,
  gadget = $25,
  reminders = $26,
  source = $27,
  created = $28,
  updated = $29,
  event_start = $30,
  event_end = $31,
  end_time_unspecified = $32,
  recurrence = $33,
  recurring_eventId = $34,
  original_start_time = $35,
  origin = $36,
  updated_at = now(),
  deleted_at = null
RETURNING id