const GRAPH_DATA = {
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('rechattest%40outlook.com')/contacts",
    "value": [{
            "@odata.etag": "W/\"EQAAABYAAACypvnacXLjTpHUqVCQrA/0AAAUxkkm\"",
            "id": "AQMkADAwATMwMAItMGM5Zi1hN2FjLTAwAi0wMAoARgAAA3gDFWbFYpFEqivhB4wN1cQHALKm_dpxcuNOkdSpUJCsD-QAAAIBDgAAALKm_dpxcuNOkdSpUJCsD-QAAAAUxIjMAAAA",
            "createdDateTime": "2018-02-02T07:40:01Z",
            "lastModifiedDateTime": "2018-02-02T07:49:02Z",
            "changeKey": "EQAAABYAAACypvnacXLjTpHUqVCQrA/0AAAUxkkm",
            "categories": [],
            "parentFolderId": "AQMkADAwATMwMAItMGM5Zi1hN2FjLTAwAi0wMAoALgAAA3gDFWbFYpFEqivhB4wN1cQBALKm_dpxcuNOkdSpUJCsD-QAAAIBDgAAAA==",
            "birthday": null,
            "fileAs": "Whitehead, Alfred",
            "displayName": "Alfred North Whitehead",
            "givenName": "Alfred",
            "initials": null,
            "middleName": null,
            "nickName": null,
            "surname": "Whitehead",
            "title": null,
            "yomiGivenName": null,
            "yomiSurname": null,
            "yomiCompanyName": null,
            "generation": null,
            "imAddresses": [],
            "jobTitle": null,
            "companyName": null,
            "department": null,
            "officeLocation": null,
            "profession": null,
            "businessHomePage": null,
            "assistantName": null,
            "manager": null,
            "homePhones": [],
            "mobilePhone": null,
            "businessPhones": [],
            "spouseName": null,
            "personalNotes": "",
            "children": [],
            "emailAddresses": [{
                "name": "jjjjjjj@oooooo.yyyyyy",
                "address": "jjjjjjj@oooooo.yyyyyy"
            }],
            "homeAddress": {},
            "businessAddress": {},
            "otherAddress": {}
        },
        {
            "@odata.etag": "W/\"EQAAABYAAACypvnacXLjTpHUqVCQrA/0AAATOh48\"",
            "id": "AQMkADAwATMwMAItMGM5Zi1hN2FjLTAwAi0wMAoARgAAA3gDFWbFYpFEqivhB4wN1cQHALKm_dpxcuNOkdSpUJCsD-QAAAIBDgAAALKm_dpxcuNOkdSpUJCsD-QAAAATOIULAAAA",
            "createdDateTime": "2018-01-31T17:48:32Z",
            "lastModifiedDateTime": "2018-01-31T17:48:33Z",
            "changeKey": "EQAAABYAAACypvnacXLjTpHUqVCQrA/0AAATOh48",
            "categories": [],
            "parentFolderId": "AQMkADAwATMwMAItMGM5Zi1hN2FjLTAwAi0wMAoALgAAA3gDFWbFYpFEqivhB4wN1cQBALKm_dpxcuNOkdSpUJCsD-QAAAIBDgAAAA==",
            "birthday": null,
            "fileAs": "Amiri, Javad",
            "displayName": "Javad Amiri",
            "givenName": "Javad",
            "initials": null,
            "middleName": null,
            "nickName": null,
            "surname": "Amiri",
            "title": null,
            "yomiGivenName": null,
            "yomiSurname": null,
            "yomiCompanyName": null,
            "generation": null,
            "imAddresses": [],
            "jobTitle": null,
            "companyName": null,
            "department": null,
            "officeLocation": null,
            "profession": null,
            "businessHomePage": null,
            "assistantName": null,
            "manager": null,
            "homePhones": [],
            "mobilePhone": "099988883",
            "businessPhones": [],
            "spouseName": null,
            "personalNotes": "",
            "children": [],
            "emailAddresses": [{
                "name": "javad@rechat.com",
                "address": "javad@rechat.com"
            }],
            "homeAddress": {},
            "businessAddress": {},
            "otherAddress": {}
        },
        {
            "@odata.etag": "W/\"EQAAABYAAACypvnacXLjTpHUqVCQrA/0AAAUxkkh\"",
            "id": "AQMkADAwATMwMAItMGM5Zi1hN2FjLTAwAi0wMAoARgAAA3gDFWbFYpFEqivhB4wN1cQHALKm_dpxcuNOkdSpUJCsD-QAAAIBDgAAALKm_dpxcuNOkdSpUJCsD-QAAAARzTHzAAAA",
            "createdDateTime": "2018-01-28T20:44:23Z",
            "lastModifiedDateTime": "2018-02-02T07:27:51Z",
            "changeKey": "EQAAABYAAACypvnacXLjTpHUqVCQrA/0AAAUxkkh",
            "categories": [],
            "parentFolderId": "AQMkADAwATMwMAItMGM5Zi1hN2FjLTAwAi0wMAoALgAAA3gDFWbFYpFEqivhB4wN1cQBALKm_dpxcuNOkdSpUJCsD-QAAAIBDgAAAA==",
            "birthday": null,
            "fileAs": "Svanberg, Mikael",
            "displayName": "Mikael Svanberg",
            "givenName": "Mikael",
            "initials": null,
            "middleName": null,
            "nickName": null,
            "surname": "Svanberg",
            "title": null,
            "yomiGivenName": null,
            "yomiSurname": null,
            "yomiCompanyName": null,
            "generation": null,
            "imAddresses": [],
            "jobTitle": null,
            "companyName": null,
            "department": null,
            "officeLocation": null,
            "profession": null,
            "businessHomePage": null,
            "assistantName": null,
            "manager": null,
            "homePhones": [],
            "mobilePhone": null,
            "businessPhones": [],
            "spouseName": null,
            "personalNotes": "",
            "children": [],
            "emailAddresses": [{
                "name": "tgo@kth.com",
                "address": "tgo@kth.com"
            }],
            "homeAddress": {},
            "businessAddress": {},
            "otherAddress": {}
        },
        {
            "@odata.etag": "W/\"EQAAABYAAACypvnacXLjTpHUqVCQrA/0AAAXBMTW\"",
            "id": "AQMkADAwATMwMAItMGM5Zi1hN2FjLTAwAi0wMAoARgAAA3gDFWbFYpFEqivhB4wN1cQHALKm_dpxcuNOkdSpUJCsD-QAAAIBDgAAALKm_dpxcuNOkdSpUJCsD-QAAAAOsNL9AAAA",
            "createdDateTime": "2018-01-24T06:50:59Z",
            "lastModifiedDateTime": "2018-02-05T08:11:04Z",
            "changeKey": "EQAAABYAAACypvnacXLjTpHUqVCQrA/0AAAXBMTW",
            "categories": [],
            "parentFolderId": "AQMkADAwATMwMAItMGM5Zi1hN2FjLTAwAi0wMAoALgAAA3gDFWbFYpFEqivhB4wN1cQBALKm_dpxcuNOkdSpUJCsD-QAAAIBDgAAAA==",
            "birthday": "1982-02-28T00:00:00Z",
            "fileAs": "Dewey, John David",
            "displayName": "Dr. John David Dewey",
            "givenName": "John",
            "initials": null,
            "middleName": "David",
            "nickName": null,
            "surname": "Dewey",
            "title": "Dr.",
            "yomiGivenName": null,
            "yomiSurname": null,
            "yomiCompanyName": null,
            "generation": null,
            "imAddresses": [],
            "jobTitle": null,
            "companyName": "BM",
            "department": null,
            "officeLocation": null,
            "profession": null,
            "businessHomePage": null,
            "assistantName": null,
            "manager": null,
            "homePhones": [],
            "mobilePhone": "(734) 555 1212 ",
            "businessPhones": [],
            "spouseName": null,
            "personalNotes": "",
            "children": [],
            "emailAddresses": [{
                "name": "personal.john@gmail.com",
                "address": "personal.john@gmail.com"
            }],
            "homeAddress": {
                "street": "St",
                "city": "City",
                "state": "St",
                "countryOrRegion": "Argentina",
                "postalCode": "343434"
            },
            "businessAddress": {},
            "otherAddress": {}
        },
        {
            "@odata.etag": "W/\"EQAAABYAAACypvnacXLjTpHUqVCQrA/0AAAXBMTX\"",
            "id": "AQMkADAwATMwMAItMGM5Zi1hN2FjLTAwAi0wMAoARgAAA3gDFWbFYpFEqivhB4wN1cQHALKm_dpxcuNOkdSpUJCsD-QAAAIBDgAAALKm_dpxcuNOkdSpUJCsD-QAAAJTpwAAAA==",
            "createdDateTime": "2017-12-31T21:03:47Z",
            "lastModifiedDateTime": "2018-02-05T08:23:07Z",
            "changeKey": "EQAAABYAAACypvnacXLjTpHUqVCQrA/0AAAXBMTX",
            "categories": [],
            "parentFolderId": "AQMkADAwATMwMAItMGM5Zi1hN2FjLTAwAi0wMAoALgAAA3gDFWbFYpFEqivhB4wN1cQBALKm_dpxcuNOkdSpUJCsD-QAAAIBDgAAAA==",
            "birthday": "1981-12-24T00:00:00Z",
            "fileAs": "Javadi, Majid",
            "displayName": "Majid Javadi",
            "givenName": "Majid",
            "initials": null,
            "middleName": null,
            "nickName": null,
            "surname": "Javadi",
            "title": null,
            "yomiGivenName": null,
            "yomiSurname": null,
            "yomiCompanyName": null,
            "generation": null,
            "imAddresses": [],
            "jobTitle": null,
            "companyName": "Dream",
            "department": null,
            "officeLocation": null,
            "profession": null,
            "businessHomePage": null,
            "assistantName": null,
            "manager": null,
            "homePhones": [],
            "mobilePhone": "09123456789",
            "businessPhones": [],
            "spouseName": null,
            "personalNotes": "Really awesome guy.",
            "children": [],
            "emailAddresses": [{
                    "name": "jalali.m@bing.com",
                    "address": "jalali.m@bing.com"
                },
                {
                    "name": "anotherJ@gmail.com",
                    "address": "anotherJ@gmail.com"
                },
                {
                    "name": "dd",
                    "address": ""
                }
            ],
            "homeAddress": {
                "street": "Street 1",
                "city": "Washington D.C.",
                "state": "Dunno",
                "countryOrRegion": "US",
                "postalCode": "9909"
            },
            "businessAddress": {
                "street": "Shoosh",
                "city": "Ad",
                "state": "Stt",
                "countryOrRegion": "Angola",
                "postalCode": "55555"
            },
            "otherAddress": {}
        }
    ]
}

const DB_DATA = [{
    abbreviated_display_name: "Mikael",
    android_address_book_id: null,
    brands: null,
    created_at: 1517828644.0374,
    deals: null,
    display_name: "Mikael Svanberg",
    id: "2acaf659-f7b0-445a-a082-a7fb1f18ac49",
    ios_address_book_id: null,
    merged: false,
    sub_contacts: [{
        android_address_book_id: null,
        attributes: {
            addresses: [{
                city: "City",
                created_at: 1517828644.10817,
                id: "471feae2-0a64-11e8-b2db-0242ac110002",
                is_primary: false,
                label: null,
                postal_code: "343434",
                state: "St",
                street_name: "St",
                type: "address",
                updated_at: 1517828644.10817,
            }],
            birthdays: [{
                birthday: 383702400000,
                created_at: 1517828644.07347,
                id: "471a9efc-0a64-11e8-b2db-0242ac110002",
                is_primary: false,
                label: null,
                type: "birthday",
                updated_at: 1517828644.07347
            }],
            companies: [{
                company: "BM",
                created_at: 1517828644.08293,
                id: "471c1106-0a64-11e8-b2db-0242ac110002",
                is_primary: false,
                label: null,
                type: "company",
                updated_at: 1517828644.08293
            }],
            emails: [{
                created_at: 1517828644.08124,
                email: "tgo@kth.com",
                id: "471bcf0c-0a64-11e8-b2db-0242ac110002",
                is_primary: false,
                label: null,
                type: "email",
                updated_at: 1517828644.08124
            }],
            last_modified_on_sources: [{
                created_at: 1517828644.06095,
                id: "4718b682-0a64-11e8-b2db-0242ac110002",
                is_primary: false,
                label: null,
                last_modified_on_source: 1517556471000,
                type: "last_modified_on_source",
                updated_at: 1517828644.06095,
            }],
            names: [{
                created_at: 1517828644.06675,
                first_name: "Mikael",
                id: "4719993a-0a64-11e8-b2db-0242ac110002",
                is_primary: false,
                label: null,
                last_name: "Svanberg",
                nickname: null,
                title: null,
                type: "name",
                updated_at: 1517828644.06676
            }],
            phone_numbers: [{
                created_at: 1517828644.09842,
                id: "471e6e06-0a64-11e8-b2db-0242ac110002",
                is_primary: false,
                label: null,
                phone_number: "+17345551212",
                type: "phone_number",
                updated_at: 1517828644.09842
            }],
            source_ids: [{
                created_at: 1517828644.05373,
                id: "47179c70-0a64-11e8-b2db-0242ac110002",
                is_primary: false,
                label: null,
                source_id: "AQMkADAwATMwMAItMGM5Zi1hN2FjLTAwAi0wMAoARgAAA3gDFWbFYpFEqivhB4wN1cQHALKm_dpxcuNOkdSpUJCsD-QAAAIBDgAAALKm_dpxcuNOkdSpUJCsD-QAAAARzTHzAAAA",
                type: "source_id",
                updated_at: 1517828644.05374
            }],
            source_types: [{
                created_at: 1517828644.08845,
                id: "471ce8a6-0a64-11e8-b2db-0242ac110002",
                is_primary: false,
                label: null,
                source_type: "External/Outlook",
                type: "source_type",
                updated_at: 1517828644.08845
            }],
            stages: [{
                created_at: 1517828644.09721,
                id: "471e3f26-0a64-11e8-b2db-0242ac110002",
                is_primary: false,
                label: null,
                stage: "General",
                type: "stage",
                updated_at: 1517828644.09722
            }],
            type: "attributes"
        },
        created_at: 1517828644.0374,
        deleted_at: null,
        id: "2acaf659-f7b0-445a-a082-a7fb1f18ac49",
        ios_address_book_id: null,
        merged: false,
        phone_numbers: null,
        refs: ["2acaf659-f7b0-445a-a082-a7fb1f18ac49"],
        type: "sub_contact",
        updated_at: 1517828644.09724,
        user: "80a227b2-29a0-11e7-b636-e4a7a08e15d4",
    }],
    summary: {
        abbreviated_display_name: "Mikael",
        display_name: "Mikael Svanberg",
        email: "tgo@kth.com",
        first_name: "Mikael",
        last_name: "Svanberg",
        legal_first_name: "Mikael",
        legal_full_name: "Mikael Svanberg",
        legal_last_name: "Svanberg",
        legal_middle_name: undefined,
        legal_prefix: null,
        middle_name: undefined,
        phone_number: undefined,
        title: undefined,
    },
    type: "contact",
    updated_at: 1517828644.09724,
    users: null
}]

module.exports = {
    GRAPH_DATA,
    DB_DATA
}