  INSERT INTO units(dining_length,
    dining_width,
    kitchen_length,
    kitchen_width,
    lease,
    listing,
    listing_mui,
    living_length,
    living_width,
    master_length,
    master_width,
    matrix_unique_id,
    matrix_modified_dt,
    full_bath,
    half_bath,
    beds,
    units,
    square_meters,
    created_at,
    updated_at)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        CASE WHEN $13 = '' THEN NULL ELSE $13::timestamptz END,
        $14,
        $15,
        $16,
        $17,
        $18,
        now(),
        now())
ON CONFLICT (matrix_unique_id) DO NOTHING
RETURNING id