 UPDATE deals SET
  transaction_type = $1,
  mls_number = $2,
  mls_area_major = $3,
  mls_area_minor = $4,
  list_price = $5,
  list_date = $6,
  property_type = $7,
  year_built = $8,
  city = $9,
  county = $10,
  postal_code = $11,
  address = $12,
  expiration_date = $13,
  executed_date = $14,
  option_period_end_date = $15,
  contingency_end_date $16,
  closing_date = $17,
  move_in_date = $18,
  lease_executed_date = $19,
  seller_names = $20,
  buyer_names = $21,
  co_listing_agent = $22,
  additional_notes = $23,
  updated_at = NOW()
WHERE id = $24