INSERT INTO property_units(
  dining_length,
  dining_width,
  kitchen_length,
  kitchen_width,
  lease,
  listing_mui,
  living_length,
  living_width,
  master_length,
  master_width,
  matrix_unique_id,
  matrix_modified_dt,
  full_bath,
  half_bath,
  beds,
  units,
  square_feet
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12::timestamptz,
  $13,
  $14,
  $15,
  $16,
  $17
)
ON CONFLICT (matrix_unique_id) DO UPDATE SET
  dining_length = $1,
  dining_width = $2,
  kitchen_length = $3,
  kitchen_width = $4,
  lease = $5,
  listing_mui = $6,
  living_length = $7,
  living_width = $8,
  master_length = $9,
  master_width = $10,
  matrix_modified_dt = $12,
  full_bath = $13,
  half_bath = $14,
  beds = $15,
  units = $16,
  square_feet = $17,
  updated_at = CLOCK_TIMESTAMP()
WHERE property_units.matrix_unique_id = $11