var property = require('./property.js');

module.exports = {
  "type": String,
  "id": String,
  "listing_agency_id": function(val) { expect(val).toBeTypeOrNull(String); },
  "created_at": Number,
  "updated_at": Number,
  "cover_image_url": function(val) { expect(val).toBeTypeOrNull(String); },
  "currency": String,
  "price": Number,
  "gallery_image_urls": [String],
  "matrix_unique_id": Number,
  "original_price": Number,
  "last_price": Number,
  "low_price": Number,
  "status": String,
  "association_fee": Number,
  "mls_number": String,
  "association_fee_frequency": String,
  "association_fee_includes": String,
  "association_type": String,
  "unexempt_taxes": Number,
  "financing_proposed": String,
  "list_office_mui": String,
  "list_office_mls_id": String,
  "list_office_name": String,
  "list_office_phone": String,
  "possession": String,
  "co_list_office_mui": String,
  "co_list_office_mls_id": String,
  "co_list_office_name": String,
  "co_list_office_phone": String,
  "selling_office_mui": String,
  "selling_office_mls_id": String,
  "selling_office_name": String,
  "selling_office_phone": String,
  "co_selling_office_mui": String,
  "co_selling_office_mls_id": String,
  "co_selling_office_name": String,
  "co_selling_office_phone": String,
  "list_agent_mui": String,
  "list_agent_direct_work_phone": String,
  "list_agent_email": String,
  "list_agent_full_name": String,
  "list_agent_mls_id": String,
  "co_list_agent_mui": String,
  "co_list_agent_direct_work_phone": String,
  "co_list_agent_email": String,
  "co_list_agent_full_name": String,
  "co_list_agent_mls_id": String,
  "selling_agent_mui": String,
  "selling_agent_direct_work_phone": String,
  "selling_agent_email": String,
  "selling_agent_full_name": String,
  "selling_agent_mls_id": String,
  "co_selling_agent_mui": String,
  "co_selling_agent_direct_work_phone": String,
  "co_selling_agent_email": String,
  "co_selling_agent_full_name": String,
  "co_selling_agent_mls_id": String,
  "listing_agreement": String,
  "capitalization_rate": String,
  "compensation_paid": String,
  "date_available": String,
  "last_status": String,
  "mls_area_major": String,
  "mls_area_minor": String,
  "mls": String,
  "move_in_date": String,
  "permit_address_internet_yn": Boolean,
  "permit_comments_reviews_yn": Boolean,
  "permit_internet_yn": Boolean,
  "price_change_timestamp": function(val) { expect(val).toBeTypeOrNull(String); },
  "price_change_timestamp": function(val) { expect(val).toBeTypeOrNull(String); },
  "matrix_modified_dt": String,
  "property_association_fees": String,
  "showing_instructions_type": String,
  "special_notes": String,
  "tax_legal_description": String,
  "total_annual_expenses_include": String,
  "transaction_type": String,
  "virtual_tour_url_branded": String,
  "virtual_tour_url_unbranded": String,
  "active_option_contract_date": String,
  "keybox_type": String,
  "keybox_number": String,
  "close_date": String,
  "close_price": function(val) { expect(val).toBeTypeOrNull(String); },
  "back_on_market_date": String,
  "deposit_amount": Number,
  "photo_count": Number,
  "deleted_at": null,
  "dom": function(val) { expect(val).toBeTypeOrNull(Number); },
  "cdom": function(val) { expect(val).toBeTypeOrNull(Number); },
  "property": property,
  "alerting_agent": function(val) { expect(val).toBeTypeOrNull(String); },
  "listing_agent": function(val) { expect(val).toBeTypeOrNull(String); }
};