var property = require('./property.js');

var optionalString = function(val) {
  expect(val).toBeTypeOrNull(String);
};

var optionalNumber = function(val) {
  expect(val).toBeTypeOrNull(Number);
};

var optionalBoolean = function(val) {
  expect(val).toBeTypeOrNull(Boolean);
};

module.exports = {
  "type": String,
  "id": String,
  "listing_agency_id": optionalString,
  "created_at": Number,
  "updated_at": Number,
  "cover_image_url": optionalString,
  "currency": String,
  "price": Number,
  "gallery_image_urls": function(val) { expect(val).toBeTypeOrNull([String]);},
  "matrix_unique_id": Number,
  "original_price": Number,
  "last_price": Number,
  "low_price": Number,
  "status": String,
  "association_fee": Number,
  "mls_number": String,
  "association_fee_frequency": optionalString,
  "association_fee_includes": optionalString,
  "association_type": optionalString,
  "unexempt_taxes": Number,
  "financing_proposed": optionalString,
  "list_office_mui": optionalString,
  "list_office_mls_id": optionalString,
  "list_office_name": optionalString,
  "list_office_phone": optionalString,
  "possession": optionalString,
  "co_list_office_mui": optionalString,
  "co_list_office_mls_id": optionalString,
  "co_list_office_name": optionalString,
  "co_list_office_phone": optionalString,
  "selling_office_mui": optionalString,
  "selling_office_mls_id": optionalString,
  "selling_office_name": optionalString,
  "selling_office_phone": optionalString,
  "co_selling_office_mui": optionalString,
  "co_selling_office_mls_id": optionalString,
  "co_selling_office_name": optionalString,
  "co_selling_office_phone": optionalString,
  "list_agent_mui": optionalString,
  "list_agent_direct_work_phone": optionalString,
  "list_agent_email": optionalString,
  "list_agent_full_name": optionalString,
  "list_agent_mls_id": optionalString,
  "co_list_agent_mui": optionalString,
  "co_list_agent_direct_work_phone": optionalString,
  "co_list_agent_email": optionalString,
  "co_list_agent_full_name": optionalString,
  "co_list_agent_mls_id": optionalString,
  "selling_agent_mui": optionalString,
  "selling_agent_direct_work_phone": optionalString,
  "selling_agent_email": optionalString,
  "selling_agent_full_name": optionalString,
  "selling_agent_mls_id": optionalString,
  "co_selling_agent_mui": optionalString,
  "co_selling_agent_direct_work_phone": optionalString,
  "co_selling_agent_email": optionalString,
  "co_selling_agent_full_name": optionalString,
  "co_selling_agent_mls_id": optionalString,
  "listing_agreement": optionalString,
  "capitalization_rate": optionalString,
  "compensation_paid": optionalString,
  "date_available": optionalString,
  "last_status": optionalString,
  "mls_area_major": optionalString,
  "mls_area_minor": optionalString,
  "mls": optionalString,
  "move_in_date": optionalString,
  "permit_address_internet_yn": optionalBoolean,
  "permit_comments_reviews_yn": optionalBoolean,
  "permit_internet_yn": optionalBoolean,
  "price_change_timestamp": optionalString,
  "price_change_timestamp": optionalString,
  "matrix_modified_dt": String,
  "property_association_fees": optionalString,
  "showing_instructions_type": optionalString,
  "special_notes": optionalString,
  "tax_legal_description": optionalString,
  "total_annual_expenses_include": optionalString,
  "transaction_type": optionalString,
  "virtual_tour_url_branded": optionalString,
  "virtual_tour_url_unbranded": optionalString,
  "active_option_contract_date": optionalString,
  "keybox_type": optionalString,
  "keybox_number": optionalString,
  "close_date": optionalString,
  "close_price": optionalString,
  "back_on_market_date": optionalString,
  "deposit_amount": optionalNumber,
  "photo_count": optionalNumber,
  "deleted_at": null,
  "dom": optionalNumber,
  "cdom": optionalNumber,
  "property": property,
  "alerting_agent": optionalString,
  "listing_agent": optionalString
};
