module.exports = {
  "type": String,
  "username": function(val) { expect(val).toBeTypeOrNull(String); },
  "first_name": String,
  "last_name": String,
  "email": String,
  "phone_number": String,
  "created_at": Number,
  "id": String,
  "cover_image_url": function(val) { expect(val).toBeTypeOrNull(String); },
  "profile_image_url": function(val) { expect(val).toBeTypeOrNull(String); },
  "updated_at": Number,
  "user_status": String,
  "profile_image_thumbnail_url": function(val) { expect(val).toBeTypeOrNull(String); },
  "cover_image_thumbnail_url": function(val) { expect(val).toBeTypeOrNull(String); },
  "email_confirmed": Boolean,
  "timezone": String,
  "user_code": Number,
  "user_type": String,
  "deleted_at": function(val) { expect(val).toBeTypeOrNull(String); },
  "phone_confirmed": Boolean,
  "current_time": String,
  "push_allowed": Boolean,
  "address": function(val) { expect(val).toBeTypeOrNull(String); },
  "invitation_url": String
};