INSERT INTO
    addresses(title,
              subtitle,
              street_suffix,
              street_number,
              street_name,
              city,
              state,
              state_code,
              country,
              country_code,
              unit_number,
              postal_code,
              neighborhood,
              matrix_unique_id)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14) RETURNING id
