INSERT INTO
    addresses(title,
              subtitle,
              street_prefix,
              street_number,
              street_name,
              city,
              state,
              state_code,
              country,
              country_code,
              unit_number,
              postal_code,
              neighborhood,
              location)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        ST_SetSRID(ST_MakePoint($14, $15), 4326)) RETURNING id
