INSERT INTO offices(
  board,
  email,
  fax,
  office_mui,
  office_mls_id,
  license_number,
  address,
  care_of,
  city,
  postal_code,
  postal_code_plus4,
  state,
  matrix_unique_id,
  matrix_modified_dt,
  mls_name,
  mls_id,
  mls_provider,
  nar_number,
  contact_mui,
  contact_mls_id,
  long_name,
  name,
  status,
  phone,
  other_phone,
  st_address,
  st_city,
  st_country,
  st_postal_code,
  st_postal_code_plus4,
  st_state,
  url,
  mls,
  broker_mui,
  broker_mls_id
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  CASE WHEN $14 = '' THEN NULL ELSE $14::timestamptz END,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20,
  $21,
  $22,
  $23,
  $24,
  $25,
  $26,
  $27,
  $28,
  $29,
  $30,
  $31,
  $32,
  $33::mls,
  $34,
  $35
) ON CONFLICT (matrix_unique_id, mls) DO UPDATE SET
  board = $1,
  email = $2,
  fax = $3,
  office_mui = $4,
  office_mls_id = $5,
  license_number = $6,
  address = $7,
  care_of = $8,
  city = $9,
  postal_code = $10,
  postal_code_plus4 = $11,
  state = $12,
  matrix_unique_id = $13,
  matrix_modified_dt = CASE WHEN $14 = '' THEN NULL ELSE $14::timestamptz END,
  mls_name = $15,
  mls_id = $16,
  mls_provider = $17,
  nar_number = $18,
  contact_mui = $19,
  contact_mls_id = $20,
  long_name = $21,
  name = $22,
  status = $23,
  phone = $24,
  other_phone = $25,
  st_address = $26,
  st_city = $27,
  st_country = $28,
  st_postal_code = $29,
  st_postal_code_plus4 = $30,
  st_state = $31,
  url = $32,
  broker_mui = $34,
  broker_mls_id = $35,
  updated_at = CLOCK_TIMESTAMP()
  WHERE offices.matrix_unique_id = $13 AND offices.mls = $33::mls
RETURNING id
